version: "3"

services:
    nginx:
        container_name: nginx
        build:
            context: .
            dockerfile: nginx.dockerfile
        ports:
            - "80:80"
        volumes:
            - ./:/var/www/html
        networks:
            - app
    php:
        container_name: php
        build:
            context: .
            dockerfile: php.dockerfile
        env_file:
            -   .env.example
        volumes:
            - ./:/var/www/html
        ports:
            - "9000:9000"
        networks:
            - app
networks:
    app:
